version: '3.4'

services:
    imovie:
        build:
            context: .
            dockerfile: Dockerfile
        image: imovie-image
        container_name: imovie-container
        restart: always
        command: python run.py
        environment:
            - EXCLUSIONS
            - ANNOTATIONS

        stdin_open: true
        tty: true

        volumes:
            - .:/home/app
            - ../live_photos_volume:/home/videos



